### ISSUE TITLE
set-env is no longer supported

### ISSUE THREAD

**Issue by Joseph-Duty-VA** [rajyraman/powerapps-solution-extract#1]
copying issue from incorrect repo/action to correct one: "I'm giving this action a try, but set-env now appears to be disabled, so it breaks (actions/toolkit#641). Any plans to update this action to eliminate reference?"

**Comment by rajyraman** [comment]
@Joseph-Duty-VA - Fixed this in v1.3. I also added a optional parameter for specifying default branch name, as master is not always the default branch. It defaults to "main" as specified in readme.

**Comment by Joseph-Duty-VA** [comment]
Re-tested and this works great - thanks for fixing!
